# Generated by Django 4.0.1 on 2022-02-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requires_extra_time',
        ),
        migrations.AddField(
            model_name='user',
            name='required_extra_time',
            field=models.IntegerField(default=0),
        ),
    ]
