# Generated by Django 4.0.1 on 2022-01-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished')], default='in_progress', max_length=25),
        ),
    ]
