# Generated by Django 4.0.1 on 2022-02-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_alter_examattempt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="question_count",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="duration_minutes",
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("finished", "Finished"),
                    ("in_progress", "In progress"),
                ],
                default="in_progress",
                max_length=25,
            ),
        ),
    ]
