# Generated by Django 4.0.1 on 2022-07-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examattempt_flagged_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='mode',
            field=models.IntegerField(default=0),
        ),
    ]
