# Generated by Django 4.0.1 on 2022-08-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_examattempt_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="mode",
            field=models.CharField(
                choices=[("practice", "Practice mode"), ("exam", "Exam mode")],
                default="practice",
                max_length=30,
            ),
        ),
    ]
