# Generated by Django 4.0.1 on 2022-08-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_examattempt_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='exam',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ManyToManyField(related_name='exams', to='exam.Exam'),
        ),
    ]
