# Generated by Django 4.0.1 on 2022-08-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_examattempt_exam_examattempt_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='exam',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exams',
            field=models.ManyToManyField(to='exam.Exam'),
        ),
    ]
