# Generated by Django 4.0.1 on 2022-10-03 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_examattempt_exam_examattempt_exams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerattempt',
            options={'verbose_name': 'answer attempt', 'verbose_name_plural': 'answer attempts'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'exam', 'verbose_name_plural': 'exams'},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'verbose_name': 'exam attempt', 'verbose_name_plural': 'exam attempts'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(default=120, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_grade',
            field=models.IntegerField(default=75, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_count',
            field=models.IntegerField(default=50, verbose_name='question count'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='duration_minutes',
            field=models.IntegerField(default=120, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice mode'), ('exam', 'Exam mode')], default='practice', max_length=30, verbose_name='mode'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('in_progress', 'In progress')], default='in_progress', max_length=25, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='name'),
        ),
    ]
