# Generated by Django 4.0.1 on 2022-01-21 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam.exam",
            ),
            preserve_default=False,
        ),
    ]
