# Generated by Django 4.0.1 on 2022-10-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_question_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'question category', 'verbose_name_plural': 'question categories'},
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('multiple_select', 'Multiple select')], default='multiple_choice', max_length=30, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='name'),
        ),
    ]
